name: Playwright Multi Environment Tests

on:
  workflow_dispatch:

jobs:

  test:

    strategy:
      matrix:
        environment: [qa, stag]

    runs-on: ubuntu-latest

    environment: ${{ matrix.environment }}

    env:
      ENV: ${{ matrix.environment }}

      BASE_URL: ${{ vars.BASE_URL }}

      APP_USERNAME: ${{ secrets.APP_USERNAME }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Show selected environment
        run: |
          echo "Running on environment: $ENV"
          echo "Base URL: $BASE_URL"

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report-${{ matrix.environment }}
          path: reports/html-report/
          retention-days: 30