name: Playwright Tests

on:

  workflow_dispatch:
    inputs:

      environment:
        description: "Select environment"
        required: true
        default: "qa"
        type: choice
        options:
          - qa
          - stage
          - dev


jobs:

  test:

    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    env:
      BASE_URL: ${{ vars.BASE_URL }}

      APP_USERNAME: ${{ secrets.APP_USERNAME }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Display environment
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Base URL: $BASE_URL"
      - name: Show selected environment
        run: |
         echo "Selected environment: ${{ github.event.inputs.environment }}"
         echo "Base URL: $BASE_URL"   

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report-${{ github.event.inputs.environment }}
          path: playwright-report/